services:
  api:
    container_name: api-tasktracker
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    expose:
      - "8080"
    restart: always
    networks:
      - webnet

  nginx:
    image: nginx:alpine
    container_name: nginx-task-tracker
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
    networks:
      - webnet

networks:
  webnet:
    driver: bridge